"""
new garmin ids to strava;
not the same logic as nike_to_strava_sync
"""

import argparse
import asyncio
import os
import time
from pathlib import Path

from config import FOLDER_DICT
from garmin_connector import (
    GarminActivityScope,
    GarminDomain,
    GarminFileType,
)
from garmin_sync import download_new_activities, get_downloaded_ids
from strava_sync import run_strava_sync
from utils import make_strava_client, upload_file_to_strava

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("strava_client_id", help="strava client id")
    parser.add_argument("strava_client_secret", help="strava client secret")
    parser.add_argument("strava_refresh_token", help="strava refresh token")
    parser.add_argument(
        "token_store",
        help="path to the token file generated by get_garmin_secret.py",
    )
    parser.add_argument(
        "--is-cn",
        dest="is_cn",
        action="store_true",
        help="if garmin account is cn",
    )
    file_type_group = parser.add_mutually_exclusive_group()
    file_type_group.add_argument(
        "--gpx",
        dest="download_file_type",
        action="store_const",
        const="gpx",
        help="download GPX files (not recommended for treadmill activities)",
    )
    file_type_group.add_argument(
        "--tcx",
        dest="download_file_type",
        action="store_const",
        const="tcx",
        help="download TCX files",
    )
    file_type_group.add_argument(
        "--fit",
        dest="download_file_type",
        action="store_const",
        const="fit",
        help="download FIT files (recommended for Strava uploads)",
    )
    parser.set_defaults(download_file_type="fit")
    options = parser.parse_args()
    strava_client = make_strava_client(
        options.strava_client_id,
        options.strava_client_secret,
        options.strava_refresh_token,
    )
    token_store = Path(options.token_store)
    garmin_domain = GarminDomain.CHINA if options.is_cn else GarminDomain.GLOBAL
    file_type = GarminFileType(options.download_file_type)
    folder = FOLDER_DICT.get(file_type.value, "gpx")
    downloaded_ids = get_downloaded_ids(folder)

    new_ids, id2title = asyncio.run(
        download_new_activities(
            token_store,
            garmin_domain,
            downloaded_ids,
            GarminActivityScope.ALL,
            file_type,
        )
    )
    print(f"To upload to strava {len(new_ids)} files")
    index = 1
    for i in new_ids:
        f = os.path.join(folder, f"{i}.{file_type.value}")
        upload_file_to_strava(strava_client, f, file_type.value)
        if index % 10 == 0:
            print("For the rate limit will sleep 10s")
            time.sleep(10)
        index += 1
        time.sleep(1)

    # Run the strava sync
    run_strava_sync(
        options.strava_client_id,
        options.strava_client_secret,
        options.strava_refresh_token,
    )
