import argparse
import asyncio
from datetime import datetime
from pathlib import Path

from garmin_connector import (
    GarminActivityScope,
    GarminConnector,
    GarminDeviceMode,
    GarminDomain,
)
from strava_sync import run_strava_sync
from stravaweblib import DataFormat, WebClient
from utils import make_strava_client


async def upload_to_activities(
    garmin_client,
    strava_client,
    strava_web_client,
    data_format,
    device_mode,
):
    last_activity = await garmin_client.get_activities(0, 1)
    if not last_activity:
        print("no garmin activity")
        filters = {}
    else:
        # is this startTimeGMT must have ?
        after_datetime_str = last_activity[0]["startTimeGMT"]
        after_datetime = datetime.strptime(after_datetime_str, "%Y-%m-%d %H:%M:%S")
        print("garmin last activity date: ", after_datetime)
        filters = {"after": after_datetime}
    strava_activities = list(strava_client.get_activities(**filters))
    files_list = []
    print("strava activities size: ", len(strava_activities))
    if not strava_activities:
        print("no strava activity")
        return files_list

    # strava rate limit
    for i in sorted(strava_activities, key=lambda i: int(i.id)):
        data = strava_web_client.get_activity_data(i.id, fmt=data_format)
        files_list.append(data)
    await garmin_client.upload_strava_activities(files_list, device_mode)
    return files_list


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("strava_client_id", help="strava client id")
    parser.add_argument("strava_client_secret", help="strava client secret")
    parser.add_argument("strava_refresh_token", help="strava refresh token")
    parser.add_argument(
        "token_store",
        help="path to the token file generated by get_garmin_secret.py",
    )
    parser.add_argument("strava_email", nargs="?", help="email of strava")
    parser.add_argument("strava_password", nargs="?", help="password of strava")
    parser.add_argument("strava_jwt", nargs="?", help="jwt token of strava")
    parser.add_argument(
        "--is-cn",
        dest="is_cn",
        action="store_true",
        help="if garmin account is cn",
    )
    parser.add_argument(
        "--use_fake_garmin_device",
        action="store_true",
        default=False,
        help="whether to use a faked Garmin device",
    )
    options = parser.parse_args()
    strava_client = make_strava_client(
        options.strava_client_id,
        options.strava_client_secret,
        options.strava_refresh_token,
    )
    if options.strava_jwt:
        strava_web_client = WebClient(
            access_token=strava_client.access_token,
            jwt=options.strava_jwt,
        )
    elif options.strava_email and options.strava_password:
        strava_web_client = WebClient(
            access_token=strava_client.access_token,
            email=options.strava_email,
            password=options.strava_password,
        )
    else:
        raise ValueError(
            "Strava activity export requires STRAVA_JWT or email and password"
        )

    garmin_domain = GarminDomain.CHINA if options.is_cn else GarminDomain.GLOBAL
    device_mode = (
        GarminDeviceMode.FAKE_GARMIN
        if options.use_fake_garmin_device
        else GarminDeviceMode.ORIGINAL
    )
    garmin_client = GarminConnector(
        Path(options.token_store),
        garmin_domain,
        GarminActivityScope.ALL,
    )
    asyncio.run(
        upload_to_activities(
            garmin_client,
            strava_client,
            strava_web_client,
            DataFormat.ORIGINAL,
            device_mode,
        )
    )

    # Run the strava sync
    run_strava_sync(
        options.strava_client_id,
        options.strava_client_secret,
        options.strava_refresh_token,
    )
